version: "3"

services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile-mysql
    image: mysql:1.0
    container_name: diary-mysql
    volumes:
      - ./db/ddl/00_create_database.sql:/docker-entrypoint-initdb.d/00_create_database.sql
      - ./db/ddl/01_create_user.sql:/docker-entrypoint-initdb.d/01_create_user.sql
      - ./db/data:/var/lib/mysql
    expose:
      - '3306'
    ports: 
      - "3306:3306"
    networks:
      - diary
  redis:
    build:
      context: ./
      dockerfile: Dockerfile-redis
    image: redis:1.0
    container_name: diary-redis
    volumes:
      - ./redis/data:/data
    expose:
      - '6379'
    ports: 
      - "6379:6379"
    networks:
      - diary

networks:
  diary:
    driver: bridge